/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n3.4.14-1-g9983d098ff"
#endif /* AVUTIL_FFVERSION_H */
